### ISSUE TITLE
map keeps blinking

### ISSUE THREAD

**Issue by john916zhang** [dburles/meteor-google-maps#38] opened 2015-04-22 14:19 UTC
Hi all,

I was happy to find this package. But when I used it, I noticed that google maps keeps blinking. I thought it's because 'exampleMapOptions' is in the 'helpers' section. So there is a Tracker.autorun session related to it. It keeps the map blinking.

Any idea?

**Comment by dburles** [comment] 2015-04-22 22:51
Hey can you possibly provide an example project that demonstrates this bug for me to test?

**Comment by lk1234** [comment] 2015-04-27 11:20
Your map is great, but I'm having the same problem when running it on a device (run ios-device). It constantly "blinks" which I assume is a refresh. The code below replicates the problem. Note, I'm also using the mdg:geolocation package. Any help in figuring this out would be appreciated:
JS
if (Meteor.isClient) {
Meteor.startup(function() {  
      GoogleMaps.load();
    });
    Template.map.helpers({  
      mapOptions: function() {
        if (GoogleMaps.loaded()) {
          return {
                  center: new Geolocation.latLng(),
                    zoom: 15
          };
        }
      }
    });
}
if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
HTML
<head>
    <script src="https://maps.googleapis.com/maps/api/js?key=mykey"&sensor=false
      type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>No Flashing Map</title>
</head>
<body>
  <div class="map-container">
    {{> map}}
  </div>
</body>
<template name="map">
        {{> googleMap name="map" options=mapOptions}}
</template> 
<template name="googleMap">
  <div style="position: absolute; width: 100%; height: 100%"></div>
</template>
/\* CSS declarations go here */
.map-container {
  width: 100%;
  max-width: 100%;
  height: 500px;
}

**Comment by dburles** [comment] 2015-04-28 00:18
@lk1234 I believe you're looking for:

```js
    exampleMapOptions: function() {
      if (GoogleMaps.loaded()) {
        var latLng = new Geolocation.latLng();
        return {
          center: new google.maps.LatLng(latLng.lat, latLng.lng),
          zoom: 8
        };
      }
    },
```

**Comment by dburles** [comment] 2015-04-28 00:37
You need to be wary of any reactive values passed into your map options as they will of course cause the map to reinitialize.

**Comment by lk1234** [comment] 2015-04-28 13:44
Thanks for getting back so quickly. Unfortunately that solution doesn't solve the issue. Still trying to figure it out. I'm working on it, but if you have any ideas...

**Comment by dburles** [comment] 2015-04-28 13:45
I would recommend placing `Geolocation.latLng();` outside of the helper. Put it in the `GoogleMaps.ready` callback instead and use `map.instance.setCenter()`

**Comment by mhurwi** [comment] 2015-04-30 16:52
I think I've encountered this same issue.  Been trying to figure it out, with no success, so I made a tiny sample app to reproduce the problem: 

https://github.com/mhurwi/meteor-maps-troubleshooting

Running the app, one map works fine, another reproduces this 'blinking' issue

**Comment by mhurwi** [comment] 2015-04-30 21:43
FYI, figured out, this is an issue with iron-router 'data' being reactive.  

```
Router.route('/shipments/:_id', function () {
  this.subscribe('shipment', this.params._id);
  this.render('shipment', this.params._id);
}, {
  name: 'shipment',
  data: function () {
    return ShipmentsCollection.findOne(this.params._id);
  }
});
```

https://github.com/mhurwi/meteor-maps-troubleshooting/blob/master/map-troubleshooting.js#L75

Removing 'data' from the route eliminates the blinking.

**Comment by dburles** [comment] 2015-05-01 01:16
hey @mhurwi thanks for the recreation, I've noticed this is catching a few people out and I'm questioning now whether the options should really be passed via a helper (since they're reactive). I'll have a look into it and get back to you.

**Comment by dburles** [comment] 2015-05-01 05:55
Thanks for the bug report, the issue should be fixed with `1.0.9`. Please let me know if the issue is fixed at your end.

**Comment by lk1234** [comment] 2015-05-01 13:28
@dburles, thanks for rethinking this. (maybe it's nothing more than further explanation in the documentation). I'm still trying to get my map to work...

**Comment by dburles** [comment] 2015-05-01 13:34
@lk1234 place reactive functions outside of the map initialization options.  Something like:

``` js
Template.map.onCreated(function() {
  GoogleMaps.ready('map', function(map) {
    var geo = new Geolocation.latLng();
    var latLng = new google.maps.LatLng(geo.lat, geo.lng);
    map.instance.setCenter(latLng);
  });
});
```

**Comment by lk1234** [comment] 2015-05-02 22:41
@dburles, Map fixed. Thank you so much...Used your suggestion above with a Tracker.autorun and it works great. Really appreciate your help and excellent documentation.

**Closed as completed** 2015-05-07 03:34 UTC

**Comment by mahiagit** [comment] 2016-12-26 05:50
This work all fine but the autorun makes the map to behave blinking in the firefox environment . working great in other browser. The helper is called again and again and makes the google map helper to initialize the map after regular interval of time even there is no change in the session on which autorun listens.
